### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by mmcasavant** [Email-builder/grunt-email-builder#35]
I've triple checked the configuration for my grunt file and made sure all the dependencies are installed for this module. Unfortunately the tool does not render the files as input in the configuration or any files at all.

http:stackoverflow.com/questions/27558551/why-wont-grunt-run-my-task/27558724#27558724

* Originally posted this under example by accident.

I've tried deleting everything and starting over. I also realized that I did not add Visual Studio to the system environment. I'm running on Windows 7, now whe
![error](https://cloud.githubusercontent.com/assets/3876161/5505878/eb92a840-8762-11e4-872d-d9020993e39f.png)
n I try to install I get the error "KeyError: 'C:\\Program Files (x86)\\Common7\\IDE\\devenv.exe gyp ERR! configure error Error: `gyp` failed with exit code: 1

**Comment by jeremypeter** [comment]
Version 3.0.0 should fix this since the Juice module we use doesn't use jsdom anymore
