### ISSUE TITLE
Error thrown on Node v0.12.0

### ISSUE THREAD

**Issue by cstauf2** [Email-builder/grunt-email-builder#39]
I had to downgrade to Node v0.10.35 in order for this plugin to work.

    Running "emailBuilder:inline" (emailBuilder) task
    >> TypeError: Cannot read property 'removeChild' of null
    
    Done, without errors.

**Comment by jeremypeter** [comment]
I'm confused, do you mean Node `v0.12.0`?

**Comment by cstauf2** [comment]
I'm sorry - yes. I was getting the above error on Node ```v0.12.0```

**Comment by mattstein** [comment]
Same problem, wasn't able to downgrade (tried Node 0.11.11, 0.11.10, 0.11.9, 0.11.8, 0.10.36, 0.10.35) due to [failed lazy symbol binding](http://stackoverflow.com/questions/14630044/node-gyp-on-osx-10-7-5-dyld-lazy-symbol-binding-failed-symbol-not-found) on OSX 10.10.2.

**Comment by jeremypeter** [comment]
Version 3.0.0 should resolve this now
