### ISSUE TITLE
grunt doesn't compile entire jade file

### ISSUE THREAD

**Issue by Gillko** [Email-builder/grunt-email-builder#42]
When using the latest version of the grunt-email-builder (3.0.1) I have a problem to compile my entire jade file. It only gives me a part of my html in the browser and it doesn't compile the second part of my code.

I don't get any errors in terminal.

I have installed the latest nodejs (v0.12.2) and latest npm (2.7.4).

It compiles the whole jade file when I have nodejs (0.10.33) and grunt-email-builder (2.0.92).

**Comment by jeremypeter** [comment]
@Gillko Would you be able to provide an example of your setup so I can we can try and replicate the issue

**Comment by Gillko** [comment]
package.json file:

{
  "name": "Grunt-EDM",
  "version": "0.3.0",
  "private": true,
  "repository": {
    "type": "git",
    "url": "git://bitbucket.org/oinkcommunication/edm.git"
  },
  "devDependencies": {
    "grunt": "^0.4.5",
    "grunt-contrib-clean": "^0.6.0",
    "grunt-contrib-compress": "^0.13.0",
    "grunt-contrib-connect": "^0.10.1",
    "grunt-contrib-imagemin": "^0.9.4",
    "grunt-contrib-jade": "^0.14.1",
    "grunt-contrib-less": "^1.0.1",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-email-builder": "^3.0.1",
    "grunt-notify": "^0.4.1",
    "grunt-open": "^0.2.3",
    "grunt-premailer": "^0.2.13",
    "grunt-text-replace": "^0.4.0",
    "imagemin-jpeg-recompress": "^4.2.1",
    "load-grunt-configs": "^0.4.3",
    "load-grunt-tasks": "^3.1.0",
    "time-grunt": "^1.1.1"
  }
}

Gruntfile.js : 

module.exports = function (grunt) {  

  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
  });

  // Load grunt configurations automatically and define the configuration for all the tasks
  var configs = require('load-grunt-configs')(grunt);
  grunt.initConfig(configs);

  // Load all grunt tasks
  require('load-grunt-tasks')(grunt);

  // Record execution time of tasks
  require('time-grunt')(grunt);

  // Create build task
  grunt.registerTask('build', [
    'jade',
    'less',
    'emailBuilder',
    'replace',
    'imagemin',
    'notify:build'
  ]);

  grunt.registerTask('export', [
    'compress',
    'premailer',
    'notify:export'
  ]);

  // Create server task
  grunt.registerTask('server', [
    'connect',
    'open',
    'notify:server',
    'watch'
  ]);

  // Create default task
  grunt.registerTask('default', [
  	'clean',
    'build',
    //'export',
    'server'
  ]);
};

**Comment by jeremypeter** [comment]
What does your `jade` and `emailBuilder` configs look like as well?

**Comment by Gillko** [comment]
jade.js

module.exports = {
  html: {
    options: {
      pretty: true
    },
    files: {
      '.cache/html/index.html': 'src/index.jade'
    }
  }
};

emailBuilder.js

module.exports = {
  inline: {
    files: {
      '.cache/inlined/index.html': '.cache/html/index.html'
    },
    options: {
      encodeSpecialChars: true,
      applyWidthAttributes: true,
      preserveMediaQueries: true
    }
  },
};

**Comment by jeremypeter** [comment]
I was able to get jade and emailBuilder to work. So does your `.cache/inlined/index.html` file only contain half the compiled code?

**Comment by Gillko** [comment]
Yeah the index.html only has half of the compiled jade code. Very strange, because I don't get errors and there is nothing wrong with my jade file.

**Comment by wardoost** [comment]
Hi, I'm Gillko his colleague and I have also been looking into this. It looks like there is some kind of limit in emailbuilder task.  The output after this task doesn't get longer than ± 85000 characters. Is it possible there is some kind of limit in the dependencies?

**Comment by yargalot** [comment]
Well, it could be, but its hard to know without a file of that size to test on and as long as the jade compilation is putting out the correct html. Can you post the last line of the inlined html here? Think there should be some answers there.

**Comment by jeremypeter** [comment]
It was an issue with the `email-builder-core`. It was basically only buffering the first bit of data and not waiting for the rest. It should be fixed in `v1.1.3` of `email-builder-core`. So all you should need to do is `npm i grunt-email-builder --save-dev` again

**Comment by wardoost** [comment]
Great! It looks like it works now. Thanks Jeremy :)
