### ISSUE TITLE
XHTML tags not being preserved

### ISSUE THREAD

**Issue by gunnx** [Email-builder/grunt-email-builder#43]
My source html file uses XHTML strict, so for example I use self closing tags on the <meta> tags, but once the file is processed by email builder the self closing is removed. Is there a flag that can preserve this? Thanks.

**Comment by jeremypeter** [comment]
Looks like it just was just resolved: https://github.com/Automattic/juice/pull/109. 
Just reinstall and use option `xmlMode: true`

**Comment by gunnx** [comment]
@jeremypeter Looks like thats only in Juice > 1.2 and the current version of email builder is using v1.0.0

**Comment by jeremypeter** [comment]
We actually prefix the version using the caret: `^1.0.0`, which means we support all minor and patch versions of `1.x.x`. So all you should need to do is just run `npm install grunt-email-builder` again and that'll update the juice dependency to use `1.2.0`

**Comment by gunnx** [comment]
I updated and yes it looks like it uses 1.2 now but still the XHTML tags are not being preserved. It actually does something odd with the meta tags, it replaces the self closing meta with <meta> and then </meta>

This is my config:

```
inline: {
    options: {
      encodeSpecialChars: true,
      widthElements: "img",
      applyWidthAttributes: true,
      juice: {
        removeStyleTags: false,
        preserveImportant: true,
        xmlMode: true
      }
    },
    files: [{
      cwd: '_build/html/email/postrender',
      src: ['*.html'],
      dest: '_build/html/email/inline',
      filter: 'isFile',
      expand: true
    }]
  }
```

Any ideas?

**Comment by mbatyumov** [comment]
I found it. It's cheeriojs library. By default it use xmlMode: false. This project has dependency of email-builder-core, which has dependency of cheerio. If you open ./node_modules/grunt-email-builder/node_modules/email-builder-core/lib/utils.js and look at 59 line, you'll find that cheerio uses inline options without opportunity of configuration.

**Comment by jeremypeter** [comment]
@mbatyumov @gunnx I updated [email-builder-core](https://github.com/Email-builder/email-builder-core/commit/6d1dea762ab436adb75ac6255adaf7e9be498ae9) to add a `cheerio` option object: 

```javascript
{
  options: {
    cheerio: {
      xmlMode: true
    }
  }
}
```

Just uninstall grunt-email-builder and reinstall it and it should pull in the latest release of email-builder-core:
```bash
npm uninstall grunt-email-builder && npm install grunt-email-builder
```

Let me know if this works for you

**Comment by mbatyumov** [comment]
Yes, it works for me. It's good news for all who uses mailchimp templates. Thank you!

**Comment by gunnx** [comment]
Thanks!

**Comment by yargalot** [comment]
Should probably close this now @jeremypeter 😉
Will leave you the honour.

**Comment by jeremypeter** [comment]
Fixed https://github.com/Email-builder/grunt-email-builder/issues/43#issuecomment-185909760
