### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by iDVB** [Email-builder/grunt-email-builder#48]
Seem to be getting permission issues with Litmus task, even though I'm pretty sure my creds are correct.

```
Running "emailBuilder:litmus" (emailBuilder) task
info: Sending new test: Default Email
CONTENT-TYPE: application/xml; charset=utf-8
TRANSFER-ENCODING: chunked
CONNECTION: close
STATUS: 401 Unauthorized
STRICT-TRANSPORT-SECURITY: max-age=31536000
X-XSS-PROTECTION: 1; mode=block
X-CONTENT-TYPE-OPTIONS: nosniff
WWW-AUTHENTICATE: Basic realm="Web Password"
P3P: CP="CAO PSA OUR"
CACHE-CONTROL: no-cache
X-REQUEST-ID: a4fb9f07-a601-473e-b26c-2354fa4bd6fa
X-RUNTIME: 0.233707
X-POWERED-BY: Phusion Passenger 4.0.57
DATE: Wed, 23 Mar 2016 21:26:43 GMT
SERVER: nginx/1.7.2 + Phusion Passenger 4.0.57
---------------------
Could't authenticate you
>> Error: 401 Unauthorized
```

**Comment by jeremypeter** [comment]
Interesting, not getting this issue, could you do the following: 

1. Go to `/node_modules/email-builder-core/node_modules/litmus-api/lib/litmus-api.js` and add a `console.log(this.reqObj)` statement to [line 23](https://github.com/jeremypeter/litmus-api/blob/master/lib/litmus-api.js#L23).
1. Run the test
1. Check the command line to see if it outputs the correct username and password

**Comment by iDVB** [comment]
Def a litmus issue. I tried a different account and it worked flawlessly. Sorry to bother.
