### ISSUE TITLE
Address ongoing issue with `event-stream`

### ISSUE THREAD

**Issue by falsyvalues** [Email-builder/grunt-email-builder#52]
Please release once [this](https://github.com/Email-builder/email-builder-core/pull/19) will be merged and released in `email-builder-core`.
Thanks!

**Comment by jeremypeter** [comment]
Fixed in v2.1.2

**Comment by falsyvalues** [comment]
@jeremypeter Thanks, I think would be nice to release 4.0.1 with bumped `email-builder-core`.
